---
title: "Take-home Exercise04"
subtitle: "COVID-19 Influence on Export and Import"
author: "Luo Zheng" 
date: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
---

```{r}
pacman::p_load(scales, viridis, lubridate, ggthemes, gridExtra, readxl, knitr, data.table, CGPfunctions, ggHoriPlot, tidyverse)
```

```{r}
impodata <- read_xlsx("data/merc.xlsx",
                       sheet = "T1",
                       range = cell_rows(10:128))  %>% 
  select(`Data Series`, contains(c("2020", "2021", "2022"))) %>% 
  gather("Import_Date", "Import_Value", -`Data Series`) %>% 


expodata <- read_xlsx("data/merc.xlsx",
                       sheet = "T2",
                       range = cell_rows(10:100)) %>% 
  select(`Data Series`, contains(c("2020", "2021", "2022"))) %>% 
  gather("Export_Date", "Export_Value", -`Data Series`)
```


```{r}
impodata$`Import_Date` <- ym(impodata$`Import_Date`)
expodata$`Export_Date` <- ym(expodata$`Export_Date`)
```

```{r}
impodata$`Import_Value` <- as.numeric(impodata$`Import_Value`)
expodata$`Export_Value` <- as.numeric(expodata$`Export_Value`)
```

```{r}
impodata_million <- impodata %>% 
filter(str_detect(`Data Series`,"Million")) %>% 
  mutate(Import_Value = Import_Value * 1000) %>% 
  rename(`Import_Value(KUSD)` = "Import_Value") %>% 
  mutate(`Data Series` = str_replace_all(`Data Series`, "\\((.*?)\\)", ""))

impodata_thousand <- impodata %>% 
filter(str_detect(`Data Series`,"Thousand")) %>% 
  rename(`Import_Value(KUSD)` = "Import_Value") %>% 
  mutate(`Data Series` = str_replace_all(`Data Series`, "\\((.*?)\\)", ""))

imp <- rbind(impodata_million, impodata_thousand)
```

```{r}
imp$Import_Month <- factor(month(imp$Import_Date), 
                    levels=1:12, 
                    labels=month.abb, 
                    ordered=TRUE) 
imp$Import_Year <- year(ymd(imp$Import_Date))
```

```{r}
expodata_million <- expodata %>% 
filter(str_detect(`Data Series`,"Million")) %>% 
  mutate(Export_Value = Export_Value * 1000) %>% 
  rename(`Export_Value(KUSD)` = "Export_Value") %>% 
  mutate(`Data Series` = str_replace_all(`Data Series`, "\\((.*?)\\)", ""))

expodata_thousand <- expodata %>% 
filter(str_detect(`Data Series`,"Thousand")) %>% 
  rename(`Export_Value(KUSD)` = "Export_Value") %>% 
  mutate(`Data Series` = str_replace_all(`Data Series`, "\\((.*?)\\)", ""))
exp <- rbind(expodata_million, expodata_thousand)
```

```{r}
exp$Export_Month <- factor(month(exp$Export_Date), 
                    levels=1:12, 
                    labels=month.abb, 
                    ordered=TRUE) 
exp$Export_Year <- year(ymd(exp$Export_Date))
exp <- exp %>% 
  filter(Export_Year == c("2020", "2021", "2022"))
```


```{r}
imp_slopegraph <- imp %>% 
  mutate(Import_Year = factor(Import_Year)) %>%
  filter(Import_Year %in% c(2020, 2022))
```

```{r}
write.table (imp_slopegraph, file ="slope.xlsx", sep ="", row.names =TRUE, col.names =TRUE, quote =TRUE)
```
