---
title: "Take-home_Ex04_draft"
subtitle: "Exploration into Singapore's Trade Partners"
author: "Luo Zheng" 
date: "`r Sys.Date()`"
execute: 
  echo: true
  eval: true
  warning: false
format: html
---

```{r}
#| code-fold: true
pacman::p_load(scales, viridis, lubridate, ggthemes, gridExtra, readxl, knitr, data.table, CGPfunctions, ggHoriPlot, ggrepel, ggiraph, plotly, ggh4x, patchwork, gganimate, hrbrthemes, tidyverse)
```

```{r}
#| code-fold: true
impodata <- read_xlsx("data/merc.xlsx",
                       sheet = "T1",
                       range = cell_rows(10:128)) %>%
  select(`Data Series`, contains(c("2020", "2021", "2022"))) 

expodata <- read_xlsx("data/merc.xlsx",
                       sheet = "T2",
                       range = cell_rows(10:100)) %>%
  select(`Data Series`, contains(c("2020", "2021", "2022"))) 
```

```{r}
#| code-fold: true
impodata_pivot <- impodata %>% 
  pivot_longer( 
     cols = `2020 Dec`:`2022 Jan`, 
     names_to = "Import_Date",
     values_transform = as.numeric,
     values_to = "Import_Value") %>% 
  pivot_wider(        
    names_from = `Data Series`,
    values_from = Import_Value
  ) 

expodata_pivot <- expodata %>% 
  pivot_longer( 
     cols = `2020 Dec`:`2022 Jan`, 
     names_to = "Export_Date",
     values_transform = as.numeric,
     values_to = "Export_Value") %>% 
  pivot_wider(        
    names_from = `Data Series`,
    values_from = Export_Value
  )

impodata_pivot$`Import_Date` <- ym(impodata_pivot$`Import_Date`)
expodata_pivot$`Export_Date` <- ym(expodata_pivot$`Export_Date`)

imp <- impodata_pivot %>% 
  mutate_at(vars(contains('Million Dollars')), ~ (. *1000)) 
exp <- expodata_pivot %>% 
  mutate_at(vars(contains('Million Dollars')), ~ (. *1000)) 

colnames(imp) <- gsub(" (Million Dollars)", "", colnames(imp), fixed = TRUE)
colnames(imp) <- gsub(" (Thousand Dollars)", "", colnames(imp), fixed = TRUE)
colnames(exp) <- gsub(" (Million Dollars)", "", colnames(exp), fixed = TRUE)
colnames(exp) <- gsub(" (Thousand Dollars)", "", colnames(exp), fixed = TRUE)
```


```{r}
#| code-fold: true
imp_con <- imp %>% 
  pivot_longer(-Import_Date, 
               names_to = "Region",
               values_to = "Import_Value(KUSD)") 

imp_con$Import_Month <- factor(month(imp_con$Import_Date), 
                    levels=1:12, 
                    labels=month.abb, 
                    ordered=TRUE) 
imp_con$Import_Year <- year(ymd(imp_con$Import_Date))

exp_con <- exp %>% 
  pivot_longer(-Export_Date, 
               names_to = "Region",
               values_to = "Export_Value(KUSD)") 

exp_con$Export_Month <- factor(month(exp_con$Export_Date), 
                    levels=1:12, 
                    labels=month.abb, 
                    ordered=TRUE) 
exp_con$Export_Year <- year(ymd(exp_con$Export_Date))
```


```{r}
#| code-fold: true
balance_data <- imp_con %>% 
  inner_join(exp_con, by = c("Region" = "Region", "Import_Date" = "Export_Date", "Import_Month" = "Export_Month", "Import_Year" = "Export_Year"))

names(balance_data) <- c("Date", "Region", "Import_Value(KUSD)", "Month", "Year", "Export_Value(KUSD)")

balance_data <- balance_data %>% 
  mutate(BOT = `Export_Value(KUSD)` - `Import_Value(KUSD)`)  %>% 
  mutate(Trade_Volume = `Export_Value(KUSD)` + `Import_Value(KUSD)`)
```

```{r}
#| fig-width: 12
#| fig-height: 10
#| code-fold: true
#| code-summary: "Plot"
balance_data %>% 
  group_by(Region) %>% 
  filter(Region !="Asia" & Region != "America" & Region != "Europe" & Region != "Africa" & Region != "Oceania" & Region != "European Union") %>% 
  ungroup() %>% 
  na.omit() %>% 
  ggplot() +
  geom_horizon(aes(x = Date, y=BOT), 
               origin = "midpoint", 
               horizonscale = 6)+
  facet_grid(`Region`~.) +
    theme_few() +
  scale_fill_hcl(palette = 'RdBu') +
  theme(panel.spacing.y=unit(0, "lines"), strip.text.y = element_text(
    size = 5, angle = 0, hjust = 0),
    legend.position = 'none',
    axis.text.y = element_blank(),
    axis.text.x = element_text(size=7),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    panel.border = element_blank()
    ) +
    scale_x_date(expand=c(0,0), date_breaks = "2 month", date_labels = "%b%y") +
  ggtitle("Singapore's Balance of Trade by Country (Jan 2020 to Dec 2022)")
```
```{r}
#| code-fold: true
bubble_data <- balance_data %>% 
  group_by(Region) %>% 
  filter(Region !="Asia" & Region != "America" & Region != "Europe" & Region != "Africa" & Region != "Oceania" & Region != "European Union") %>% 
  ungroup() %>% 
  na.omit() %>% 
  select(Region, Year, `Import_Value(KUSD)`, `Export_Value(KUSD)`, Trade_Volume) %>% 
  mutate("Import_Value(MUSD)" = `Import_Value(KUSD)`/1000) %>% 
  mutate("Export_Value(MUSD)" = `Export_Value(KUSD)`/1000) %>% 
  mutate("Trade_Volume" = Trade_Volume/1000) %>% 
  mutate_each_(funs(factor(.)), "Region") %>% 
  mutate(Year = as.integer(Year))
```

```{r}
#| code-fold: true
#| code-summary: "Plot"
#| fig-width: 9
#| fig-height: 9
ggplot(bubble_data, aes(x = `Import_Value(MUSD)`, 
                        y = `Export_Value(MUSD)`,
                      size = Trade_Volume, 
                      colour = Region)) +
  geom_point(alpha = 0.7, 
             show.legend = FALSE) +
  scale_size(range = c(2, 12)) +
  labs(title = "Singapore's Merchandise Trade Performance with Trading Partners \n Year: {frame_time}") +
  transition_time(Year) +       
  ease_aes('linear')            
```

```{r}
#| code-fold: true
top6_volume <- balance_data %>% 
  group_by(Region) %>% 
  filter(Region !="Asia" & Region != "America" & Region != "Europe" & Region != "Africa" & Region != "Oceania" & Region != "European Union") %>% 
  summarise("Total_Volume" = sum(`Trade_Volume`)) %>% 
  ungroup() %>% 
  arrange(desc(Total_Volume))
top6_volume <- top6_volume$Region[1:6]

line_top6 <- balance_data %>% 
  group_by(Region) %>% 
  filter(Region %in% top6_volume) %>% 
  ungroup() %>% 
  mutate("Import_Value(MUSD)" = `Import_Value(KUSD)`/1000) %>% 
  mutate("Export_Value(MUSD)" = `Export_Value(KUSD)`/1000)
```

```{r}
#| code-fold: true
#| code-summary: "Plot"
line_top6p <-
  ggplot(line_top6, aes(x = Date)) +
  geom_line(aes(y = `Export_Value(MUSD)`, color = "Export")) +
  geom_line(aes(y = `Import_Value(MUSD)`, color = "Import")) +
  facet_wrap(~Region, ncol = 3) + 
  stat_difference(aes(ymin = `Import_Value(MUSD)`, ymax = `Export_Value(MUSD)`), alpha = 0.3) +
  labs(x = "Time", y = "Trade Value (MUSD)", 
     title = "Import and Export Value of Singapore's Top Trading Partners (2020-2022)") +
  theme(axis.ticks = element_blank(),
        axis.text.x = element_text(size = 5),
        axis.text.y = element_text(size = 5),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6) )
```


```{r}
#| code-fold: true
#| code-summary: "Plot"
bar_top6 <- line_top6 %>% 
  select(Region, Year, `Export_Value(MUSD)`, `Import_Value(MUSD)`) %>% 
  pivot_longer(cols = `Export_Value(MUSD)`:`Import_Value(MUSD)`, names_to = "Category") %>% 
  group_by(Region, Year, Category) %>% 
  summarise("Value" = sum(`value`)) %>% 
  ungroup()

bar_top6p <-
  ggplot(bar_top6, aes(fill=Category, y=Value, x=Year)) + 
    geom_bar(position="stack", stat="identity") +
  facet_wrap(~Region,ncol = 6) +
  labs( title = "Import and Export Value of Singapore's Top Trading Partners (2020-2022)") +
  theme(axis.text.x = element_text(size = 5),
        axis.text.y = element_text(size = 5))
```

```{r}
#| code-fold: true
#| code-summary: "Plot"
#| fig-width: 12
#| fig-height: 12
subplot(bar_top6p, line_top6p, nrows = 2)
```
```{r}
#| code-fold: true
#| warning: FALSE
imp_slopegraph <- balance_data %>% 
  select(Region, Year, `Import_Value(KUSD)`) %>% 
  group_by(Region, Year) %>%
  filter(Region == c("America", "Europe", "Asia", "Africa", "Oceania")) %>% 
  summarise("Import" = sum(`Import_Value(KUSD)`)/1000) %>% 
  ungroup()

exp_slopegraph <- balance_data %>% 
  select(Region, Year, `Export_Value(KUSD)`) %>% 
  group_by(Region, Year) %>%
  filter(Region == c("America", "Europe", "Asia", "Africa", "Oceania")) %>% 
  summarise("Export" = sum(`Export_Value(KUSD)`)/1000) %>% 
  ungroup()
```


```{r}
#| code-fold: true
#| warning: FALSE
import_slope <- imp_slopegraph %>%
  mutate(Year = factor(Year, ordered = TRUE, levels = c(2020,2021,2022))) %>%
  newggslopegraph(Year, Import, Region,
                Title = "Import Value of 5 Continents",
                SubTitle = "2020-2022",
                Caption = "(million USD)")

export_slope <- exp_slopegraph %>% 
  mutate(Year = factor(Year, ordered = TRUE, levels = c(2020,2021,2022))) %>%
  newggslopegraph(Year, Export, Region,
                Title = "Export Value of 5 Continents",
                SubTitle = "2020-2022",
                Caption = "(million USD)")
grid.arrange(import_slope, export_slope, ncol = 2)
```

```{r}
#| code-fold: true
#| warning: FALSE
bot_line <- balance_data %>% 
  select(Region, Date, BOT) %>% 
  group_by(Region) %>%
  filter(Region == c("America", "Europe", "Asia", "Africa", "Oceania")) %>%
  mutate("BOT" = `BOT`/1000) %>% 
  ungroup()
```

```{r}
#| code-fold: true
#| code-summary: "Plot"
bot_line %>% 
  ggplot( aes(x=Date, y=BOT, group=Region, color=Region)) +
    geom_line() +
    geom_point() +
   geom_hline(yintercept=0, color="orange", size=.5) +
    scale_color_viridis(discrete = TRUE) +
    ggtitle("Singapore's Balance of Trade from 5 Continents") +
    theme_ipsum() +
    ylab("Balance of Trade (Million USD)") +
    transition_reveal(Date)
```

```{r}
#| code-fold: true
#| warning: FALSE
cycle_data <- balance_data %>% 
  select(Region, Month, Year, BOT) %>% 
  group_by(Region) %>% 
  filter(Region == "Mainland China") %>% 
  mutate("Mainland_China" = `BOT`/1000) %>% 
  ungroup() %>% 
  select(Mainland_China, Month, Year)

hline.data <- cycle_data %>% 
  group_by(Month) %>%
  summarise(avgvalue = mean(`Mainland_China`))
```


```{r}
#| code-fold: true
#| code-summary: "Plot"
ch_import <- cycle_data %>% 
  ggplot() +
  geom_line(aes(x=Year, 
                y=Mainland_China, 
                group=Month), 
            colour="black") +
  facet_wrap(~Month, ncol = 6) +
  geom_hline(yintercept=0, color="grey", size=.5) +
    geom_hline(aes(yintercept=avgvalue), 
             data=hline.data, 
             linetype=6, 
             colour="red", 
             size=0.5) + 
  labs(axis.text.x = element_blank(),
       title = "Singapore Balance of Trade of China, Jan 2020-Dec 2022") +
  xlab("") +
  ylab("Balance of Trade (Million USD)") +
    theme(axis.text.x = element_text(size = 3),
        axis.text.y = element_text(size = 5))
ggplotly(ch_import)
```
